# MAP 13*11

# REWARD
REWARD_WALL = -286
REWARD_PROTECTION_TOUCHED = -100
REWARD_ENEMY_MISSILE_TOUCHED = -100
REWARD_DEFAULT = -1
REWARD_ENEMY_KILLED = 200
REWARD_STAGE_CLEAR = 1000

# MAP
MAP_START_AGENT = '.'
MAP_ENEMY = '-'
MAP_PROTECTION = '@'
MAP_WALL = '#'
MAP_ENEMY_MISSILE = '!'
MAP_AGENT_MISSILE = '|'

MAP_TARGET = MAP_ENEMY

# AGENT
ACTION_LEFT, ACTION_RIGHT, ACTION_SHOOT = 'L', 'R', 'S'
ACTIONS = [ACTION_LEFT, ACTION_RIGHT, ACTION_SHOOT]

MOVES = {ACTION_LEFT: (-1, 0),
         ACTION_RIGHT: (1, 0),
         ACTION_SHOOT: (0, 0)
         }

SPRITE_SCALE = 0.4
SPRITE_SIZE = int(SPRITE_SCALE * 128)
